import type { SoftwareBuildContext } from '../contracts/types';

export const homeScreenHtml = (context: SoftwareBuildContext) =>
  `<section class="screen active" data-screen="home"><section class="hero"><div><p class="eyebrow">${context.blueprint.label}</p><h2>${
    context.name
  }</h2><p>${
    context.softwareProcess.requirementBreakdown.productSummary
  }</p><div class="status-bar"><span>Production-shaped preview</span><span>Role-aware screens</span><span>SQLite schema</span><span>PWA-ready shell</span></div><div class="kit-badges"><span>LandingPage pattern</span><span>Root shell</span><span>GlobalHeader</span><span>CreateModal</span></div></div><a class="hero-link" href="#/login">Open demo login</a></section><section class="panel"><h2>User stories and build tasks</h2><div class="crud-grid">${context.softwareProcess.userStories
    .slice(0, 4)
    .map((story) => `<article class="form-card"><strong>User story</strong><p>${story}</p></article>`)
    .join('')}</div></section><section class="module-strip">${context.modules
    .map((module) => `<span>${module}</span>`)
    .join('')}</section></section>`;

export const authScreensHtml = () =>
  `<section class="screen" data-screen="login"><section class="panel" data-ui-kit-component="CreateModal"><h2>Login</h2><p>Demo authentication screen for role simulation. Production auth must be integrated before real use.</p><div class="auth-grid"><form class="form-card" data-auth-form="login"><label data-ui-kit-component="FormField">Email<input name="email" value="admin@example.test" aria-label="Email"/></label><label data-ui-kit-component="FormField">Password<input name="password" type="password" value="demo-password" aria-label="Password"/></label><label data-ui-kit-component="FormField">Role<select name="role" data-role-select><option value="organization_admin">Practice Admin</option><option value="manager">Manager</option><option value="user">Operator</option><option value="guest">Guest</option><option value="super_admin">Super Admin</option></select></label><div class="actions"><button type="button" data-action="login">Sign in</button><a href="#/signup">Create account</a></div></form><article class="form-card"><h3>Demo roles</h3><p>Switch roles to test protected, forbidden, and admin-only route states.</p></article></div></section></section><section class="screen" data-screen="signup"><section class="panel" data-ui-kit-component="CreateModal"><h2>Signup</h2><p>Invite-based onboarding screen with organization, role, and consent capture.</p><form class="auth-grid" data-auth-form="signup"><label data-ui-kit-component="FormField">Full name<input name="fullName" required aria-label="Full name"/></label><label data-ui-kit-component="FormField">Work email<input name="email" required aria-label="Work email"/></label><label data-ui-kit-component="FormField">Organization<input name="organization" required aria-label="Organization"/></label><label data-ui-kit-component="FormField">Requested role<select name="requestedRole"><option>Front Desk</option><option>Provider</option><option>Billing Specialist</option><option>Patient Portal</option></select></label><label data-ui-kit-component="FormField">Compliance acknowledgement<textarea name="acknowledgement" aria-label="Compliance acknowledgement">Demo data only. Production deployment needs compliance review.</textarea></label><div class="actions"><button type="button" data-action="login">Request invite</button></div></form></section></section>`;
