import { uiKitComponentContracts, uiKitComponents, uiKitPagePatterns, uiKitScreens, uiKitVisualTokens } from '../../ui-kit';
import type { AdvancedSoftwareFile, SoftwareBuildContext } from './types';

export const buildManifestFile = (context: SoftwareBuildContext): AdvancedSoftwareFile => ({
  path: 'app.manifest.json',
  kind: 'json',
  content: JSON.stringify(
    {
      name: context.name,
      slug: context.appSlug,
      framework: context.template.framework,
      database: context.database,
      domain: context.blueprint.id,
      modules: context.modules,
      routes: context.blueprint.routes,
      tables: context.blueprint.tables,
      workflows: context.blueprint.workflows,
      seedRecords: context.blueprint.records.length,
      uiKit: {
        source: 'sanitized-ui-kit-cache',
        components: uiKitComponents,
        screens: uiKitScreens,
        componentContracts: uiKitComponentContracts,
        pagePatterns: uiKitPagePatterns,
        visualTokens: uiKitVisualTokens,
        usedComponents: [
          'Root',
          'Sidebar',
          'GlobalHeader',
          'MetricCard',
          'SparklineChart',
          'EnhancedDataTable',
          'CreateModal',
          'FormField',
          'Panel',
          'LogViewerTable',
        ],
        componentUsageByFile: {
          'src/app/components/AppLayout.tsx': ['Root', 'Sidebar', 'GlobalHeader'],
          'src/app/components/RecordsTable.tsx': ['EnhancedDataTable'],
          'src/app/components/MonitoringPanel.tsx': ['MetricCard', 'SparklineChart'],
          'src/app/pages/AuthScreens.tsx': ['CreateModal', 'FormField'],
          'src/app/pages/ReportsPage.tsx': ['Panel', 'MetricCard', 'SparklineChart'],
        },
      },
      softwareProcess: context.softwareProcess,
      matrices: {
        featurePatterns: context.softwareProcess.featurePatternMatrix,
        routeAuthRbac: context.softwareProcess.routeAuthRbacMatrix,
        crudOperations: context.softwareProcess.crudOperationMatrix,
        backendContracts: context.softwareProcess.backendContractMatrix,
        screenStates: context.softwareProcess.screenStateMatrix,
        tests: context.softwareProcess.testCoverageMatrix,
      },
      backend: context.softwareProcess.backendArchitecture,
      pwa: { manifest: 'pwa/manifest.webmanifest', offlineFallback: 'pwa/offline.html' },
      connectivity: context.softwareProcess.connectivity,
      verification: context.softwareProcess.verification,
      valueScore: context.softwareProcess.valueScore,
      definitionOfDone: context.softwareProcess.definitionOfDone,
      requirementCompletionChecklist: context.softwareProcess.requirementCompletionChecklist,
      deployment: { ...context.softwareProcess.deployment, entryFile: 'index.html', hostable: true },
      brandingAudit: { neutralGeneratedProject: true, userFacingPlatformBrandRemoved: true },
    },
    null,
    2,
  ),
});
