import { InMemoryRepository, type BaseRecord } from './entity/repository.js';
import { makeId, nowIso, type PackageHealth, type PackageModule, type RequestContext } from './contracts.js';
import { createStubLauncher } from './launcher.js';
import { createPackageObservability } from './observability.js';
import { advancedAgentRegistry, advancedAgentNames } from './backend/agents/index.js';
export type AdvancedAgentKind = 'planner-agent' | 'researcher-agent' | 'software-builder-agent' | 'deployment-agent' | 'memory-agent' | 'output-designer-agent' | 'image-gis-agent' | 'data-analyst-agent' | 'platform-fix-agent' | 'process-monitor-control-agent' | 'swarm-coordinator-agent';
export interface AdvancedAgentPlan extends BaseRecord { kind: AdvancedAgentKind; objective: string; steps: string[]; status: 'planned' | 'running' | 'completed'; output?: string; }
const plans = new InMemoryRepository<AdvancedAgentPlan>('advanced_plan'); const observability = createPackageObservability('@connectingmatrix/ai-agents-advanced');
let runner: ((plan: AdvancedAgentPlan, context: RequestContext) => Promise<string>) | undefined;
export const AdvancedAIAgents = { bindLogger(logger: unknown) { observability.bindLogger(logger as never); return AdvancedAIAgents; }, bindSockets(sockets: unknown) { observability.bindSockets(sockets as never); return AdvancedAIAgents; }, setRunner(adapter: (plan: AdvancedAgentPlan, context: RequestContext) => Promise<string>) { runner = adapter; return AdvancedAIAgents; }, agents() { return advancedAgentRegistry; }, plan(input: { kind?: AdvancedAgentKind; objective: string; steps?: string[] }, context: RequestContext = {}) { const steps = input.steps?.length ? input.steps : [`Clarify ${input.objective}`, 'Research constraints', 'Design output', 'Validate result']; return plans.create({ kind: input.kind ?? 'planner-agent', objective: input.objective, steps, status: 'planned' }, context); }, list(context: RequestContext = {}) { return plans.list(context, { limit: 500 }); }, getObject(id: string, context: RequestContext = {}) { return plans.get(id, context); }, async executePlan(id: string, context: RequestContext = {}) { const plan = plans.get(id, context); if (!plan) throw new Error(`Advanced plan not found: ${id}`); plans.update(id, { status: 'running' }, context); const agent = advancedAgentRegistry.find((candidate) => candidate.name === plan.kind); const output = runner ? await runner(plan, context) : agent ? (await agent.run({ objective: plan.objective, context: context as unknown as Record<string, unknown> })).output : `Executed ${plan.kind}: ${plan.steps.join(' -> ')}`; await observability.emit('info','execute-plan',{ id, kind: plan.kind }); return plans.update(id, { status: 'completed', output }, context); }, async runAgent(name: string, input: { objective: string; context?: Record<string, unknown> }, context: RequestContext = {}) { const agent = advancedAgentRegistry.find((candidate) => candidate.name === name); if (!agent) throw new Error(`Advanced agent not found: ${name}`); await observability.emit('info','run-agent',{ name }); return agent.run({ ...input, context: input.context ?? (context as unknown as Record<string, unknown>) }); }, designOutput(input: { title: string; schema?: Record<string, unknown>; sample?: unknown }, context: RequestContext = {}) { const plan = plans.create({ kind: 'output-designer-agent', objective: input.title, steps: ['draft schema', 'render editable designer', 'validate sample'], status: 'completed', output: JSON.stringify(input) }, context); return { id: plan.id, mode: 'connected', title: input.title, editable: true, schema: input.schema ?? {}, sample: input.sample ?? null }; }, launcher: createStubLauncher, health(): PackageHealth { return { name: '@connectingmatrix/ai-agents-advanced', status: 'ok', checkedAt: nowIso(), details: { plans: plans.list({ root: true }).total, runner: Boolean(runner), agentFolders: advancedAgentNames, usesCoreContracts: '@connectingmatrix/ai-agents/agent-contracts', workflowTreeNodeAgentsOwnedHere: false, observability: observability.health().details } }; } };
export const graphql = { namespace: 'advancedAiAgents', typeDefs: `type AdvancedAgentPlan { id: ID!, kind: String!, objective: String!, steps: [String!]!, status: String!, output: String } type Query { advancedAgentPlans: [AdvancedAgentPlan!]!, advancedAgentsLauncher: String! } type Mutation { advancedAgentPlan(kind: String, objective: String!): AdvancedAgentPlan!, advancedAgentExecute(id: ID!): AdvancedAgentPlan! }`, resolvers: { Query: { advancedAgentPlans: (_: unknown, __: unknown, ctx: RequestContext) => AdvancedAIAgents.list(ctx).items, advancedAgentsLauncher: (_: unknown, __: unknown, ctx: RequestContext) => JSON.stringify(createStubLauncher(ctx)) }, Mutation: { advancedAgentPlan: (_: unknown, args: { kind?: AdvancedAgentKind; objective: string }, ctx: RequestContext) => AdvancedAIAgents.plan(args, ctx), advancedAgentExecute: (_: unknown, args: { id: string }, ctx: RequestContext) => AdvancedAIAgents.executePlan(args.id, ctx) } }, migrations: ['migrations/0001_init.sql'] };
export function createPackage(): PackageModule { return { name: '@connectingmatrix/ai-agents-advanced', version: '0.3.0', health: () => AdvancedAIAgents.health(), graphql, migrations: graphql.migrations, launcher: createStubLauncher, routes: [{ method: 'GET', path: '/ai-agents-advanced/health', handler: () => AdvancedAIAgents.health() }, { method: 'GET', path: '/ai-agents-advanced/launcher', handler: (request) => createStubLauncher((request as { context?: RequestContext }).context ?? {}) }], runtime: { AdvancedAIAgents, advancedAgentRegistry, observability } }; }
export * from './contracts.js'; export * from './package-structure.js'; export * from './launcher.js'; export * from './backend/agents/index.js';
