export { planner_agent } from './planner-agent/index.js';
export { researcher_agent } from './researcher-agent/index.js';
export { software_builder_agent } from './software-builder-agent/index.js';
export { deployment_agent } from './deployment-agent/index.js';
export { data_analyst_agent } from './data-analyst-agent/index.js';
export { image_gis_agent } from './image-gis-agent/index.js';
export { memory_agent } from './memory-agent/index.js';
export { platform_fix_agent } from './platform-fix-agent/index.js';
export { process_monitor_control_agent } from './process-monitor-control-agent/index.js';
export { output_designer_agent } from './output-designer-agent/index.js';
export { swarm_coordinator_agent } from './swarm-coordinator-agent/index.js';
import { planner_agent } from './planner-agent/index.js';
import { researcher_agent } from './researcher-agent/index.js';
import { software_builder_agent } from './software-builder-agent/index.js';
import { deployment_agent } from './deployment-agent/index.js';
import { data_analyst_agent } from './data-analyst-agent/index.js';
import { image_gis_agent } from './image-gis-agent/index.js';
import { memory_agent } from './memory-agent/index.js';
import { platform_fix_agent } from './platform-fix-agent/index.js';
import { process_monitor_control_agent } from './process-monitor-control-agent/index.js';
import { output_designer_agent } from './output-designer-agent/index.js';
import { swarm_coordinator_agent } from './swarm-coordinator-agent/index.js';
export const advancedAgentRegistry = [planner_agent, researcher_agent, software_builder_agent, deployment_agent, data_analyst_agent, image_gis_agent, memory_agent, platform_fix_agent, process_monitor_control_agent, output_designer_agent, swarm_coordinator_agent];
export const advancedAgentNames = advancedAgentRegistry.map((agent) => agent.name);
